### ISSUE TITLE
Error when adding a user

### ISSUE THREAD

**Issue by LoriL2** [sjelfull/Craft-UserCreator#3]
I can't seem to get UserCreator to work now.  I'm using Craft 2.6.2949 and UserCreator 1.0.3.  I filled out all of the fields and get this error:

`CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userId' cannot be null`

Note that I am using "use email as username" in my Craft settings and I know that there is still an outstanding issue with leaving the username blank so I filled both "email" and "username" fields in with the user's email address.

I just uninstalled then reinstalled the plugin using the Craft Plugin Settings tab.  I was able to get the plugin to work 2 times out of 6 tries.  Not sure why it worked those two times and not the other times.

**Comment by sjelfull** [comment]
Thanks for reporting this. Could you tell me what steps I can do to try to reproduce this?

**Comment by LoriL2** [comment]
I couldn't figure out a pattern to be honest. I filled in the first and last name columns and then used an email address for both email and username. The first time I did it, I copied and pasted 2 users from an excel document and got the error upon submission. Then tried it again, error again. Then I typed in 1 user and that worked. I looked in the users section and saw 2 of the other users that apparently were successful even though I got an error. So I tried again and it didn't work a few more times. Not sure if this matters but I turned on the switch for activate users but turned the two underneath off.

**Comment by sjelfull** [comment]
Great info. I'm working on a new release now that hopefully will resolve this, as well as have more robust error handling.

I'll notify you once I get it out.

**Comment by sjelfull** [comment]
I've pushed a new release here: https://github.com/sjelfull/Craft-UserCreator/releases/tag/1.0.4

Could you test this and see if your still experiencing any issues?

**Comment by LoriL2** [comment]
I tried the new version but running into the previous issue with the email as username.  I typed in two new users and when I submitted I got the error "email can't be blank".  I filled out the the email for both users but my guess is that I'm running into the other problem with using the email as username.  I am unable to test the issue above because of this issue.

**Comment by sjelfull** [comment]
I'm focusing on the Craft 3 version, and won't be revisiting this.
